services:
  # db:
  #   image: postgres:15
  #   container_name: postgres_db
  #   env_file: .env
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  web:
    build: .
    container_name: fastapi_app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    #depends_on:
      # db:
      #   condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
