"""descripcion

Revision ID: 429563bb5914
Revises: 
Create Date: 2025-06-28 01:17:22.628208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429563bb5914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PERIODO', 'codigo_periodo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('PERIODO', 'nombre_periodo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=180),
               existing_nullable=False)
    op.alter_column('PERIODO', 'mes',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=35),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PERIODO', 'mes',
               existing_type=sa.String(length=35),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('PERIODO', 'nombre_periodo',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('PERIODO', 'codigo_periodo',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
