"""descripcion

Revision ID: 429563bb5914
Revises: 
Create Date: 2025-06-28 01:17:22.628208

"""
from alembic import op
import sqlalchemy as sa
   
# revision identifiers, used by Alembic.
revision = '429563bb5914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Actualizar el esquema de la base de datos modificando los tipos de columna de la tabla PERIODO.
    **Objetivo:** Ampliar la longitud de los campos `codigo_periodo`, `nombre_periodo` y `mes` en la tabla
    `PERIODO` para permitir mayor flexibilidad en los datos registrados.
    
    `codigo_periodo`: de `VARCHAR(20)` a `VARCHAR(150)`
    `nombre_periodo`: de `VARCHAR(50)` a `VARCHAR(180)`
    `mes`: de `VARCHAR(15)` a `VARCHAR(35)`
    """    
    
    # ### commands auto generated by Alembic
    op.alter_column('PERIODO', 'codigo_periodo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('PERIODO', 'nombre_periodo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=180),
               existing_nullable=False)
    op.alter_column('PERIODO', 'mes',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=35),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    """Función de reversión de la migración. Revertir los cambios aplicados por la función upgrade() 
    en la tabla PERIODO
    Revierte el tamaño de las columnas de la tabla PERIODO a sus valores originales:

    mes: de 35 caracteres de vuelta a 15
    nombre_periodo: de 180 caracteres de vuelta a 50
    codigo_periodo: de 150 caracteres de vuelta a 20
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PERIODO', 'mes',
               existing_type=sa.String(length=35),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('PERIODO', 'nombre_periodo',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('PERIODO', 'codigo_periodo',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
